### ISSUE TITLE
Interpunkcja

### ISSUE THREAD

**Issue by WojAbuk** [coders-school/git-checker#21]
[PL]„Ale już widziałem zeznanie podatkowe jednego programisty wkomitowane do repozytorium. A modyfikacja historii repo to nie taka prosta sprawa.” 
W języku polskim nie powinno zaczynać się zdania od "a" i "ale". Mimo zdaniem "Ale" jest zbędne, a "A" jest w środku zdania, więc powinno być z makiem litery i przed nim powinien być przecinek, a nie kropka.

**Comment by ziobron** [comment]
🏅 2 XP granted for @WojAbuk
Thanks for raising this Issue to help to make the course better!

**Comment by ziobron** [comment]
@WojAbuk fixed. Please provide the exact occurrence of the issue by providing a filename of a link to the lesson. It would be easier to fix it in the future.
