### ISSUE TITLE
CI - 'main.cpp' created ❌ Failed

### ISSUE THREAD

**Issue by bartosz-gruszczyk** [coders-school/git-checker#24]
Hi! My homework hasn't passed one test: 'main.cpp' created
I created the file main.cpp by typing `code main.cpp` in terminal. It runs VSC with opened new file main.cpp. It was just faster for me considering I need to write some code there. In the instructions for the homework it's not said I need to create an empty file main.cpp first, so I think the test should pass. Guess the others could use any editor the same way. Maybe we should remove this part of the test and only check if the repository contains main.cpp?
I suspect if I used `touch main.cpp` it would pass. Should I correct my solution and rerun the tests?

PS. It's my first issue post on GH, so forgive me if I've done something wrong.

**Comment by ziobron** [comment]
🏅 2 XP granted for @bartosz-gruszczyk
Thanks for raising this Issue to help to make the course better!

**Comment by ziobron** [comment]
Linking #23
