### ISSUE TITLE
Test failed - issues in the test script

### ISSUE THREAD

**Issue by octopus1906** [coders-school/git-checker#30]
Test of my homework fails because of two issues reported, they are a bugs in my opinion:

➡️  'main.cpp' created ❌ Failed
I created main.cpp file using 'vim' instead of 'touch' which the most probably was expected here. As I noticed this is not the first issue which reports this problem - is it possible to update the test script to make it more flexible?

➡️  HEAD moved to "Initial commit" ❌ Failed
I moved the HEAD using command 'git rebase -i', the result is exactly the same as in case of 'git reset' which was supposed to be used, however tests did not pass.

Let me know if I need to correct my solution. BR

**Comment by ziobron** [comment]
🏅 2 XP granted for @octopus1906
Thanks for raising this Issue to help to make the course better!

**Comment by ziobron** [comment]
Linking #29
