### ISSUE TITLE
History test issue

### ISSUE THREAD

**Issue by TomaszWeglinski2** [coders-school/git-checker#49]
I really have no idea why in my case it does not pass the test as below

➡️  Pushed to the remote repo ❌ Failed

I had a problem along the way but I think I fixed everything and as a result the repo is as expected.

The fact that the previous tests had something to check proves that the push was successful, so I am reporting this as an issue 

[link](https://github.com/coders-school/git-checker/pull/31/checks?check_run_id=2490920653#step:6:15)

**Comment by ziobron** [comment]
🏅 2 XP granted for @TomaszWeglinski2
Thanks for raising this Issue to help to make the course better!

**Comment by ziobron** [comment]
From a very quick look - probably you are using main branch instead of master. You can try and play with this one.
I will try to fix it from my side by the end of this week.

**Comment by TomaszWeglinski2** [comment]
Thanks for your help!
