### ISSUE TITLE
Git homework description suggestion

### ISSUE THREAD

**Issue by michalsoloducha** [coders-school/git-checker#74]
In the [GIT homework](https://kursy.coders.school/szkolenie.html?tid=15&lid=254) I got a little bit confused at one point and I would change:
"Zrób push z i na gałąź master"
into "Zrób push z lokalnej gałęzi master na znalną"
The initial description was correct but I think the proposed version is easier to understand.

**Comment by ziobron** [comment]
🏅 2 XP granted for @michalsoloducha
Thanks for raising this Issue to help to make the course better!
